feat: Hangman Game java based project
Codesee-io/oss-port pull request #107
Opened 2021-09-27 13:41 UTC by mradulrathore

2021-09-27 16:58 UTC, ramonh requested changes
Thank you so much for your contribution, @mradulrathore!

I left one request in the pull request, but otherwise looking good!

2021-09-27 16:58 UTC, ramonh commented on projects/mradulrathore/HangmanGame.mdx
> +To run it, download the files and run the Hangman.java file
Could you perhaps please provide an example command for running this?

I'm not entirely familiar with running Java files, and as a learner would appreciate reproducible steps for running the game.

2021-09-28 06:52 UTC, mradulrathore commented on projects/mradulrathore/HangmanGame.mdx
> +To run it, download the files and run the Hangman.java file
thanks for reviewing! I've added the description for running the application.

2021-09-28 12:06 UTC, ramonh approved these changes
Looks great, thank you!

I am terrible at this, and have lost three times in a row 😂 

Welcome to the port!

2021-09-28 12:06 UTC, merged

2021-09-29 15:21 UTC, mradulrathore commented
I can relate. Sometimes it happens with me as well😂
Thank you for the warm welcome and looking forward to contributing!