Add dnnrly projects
Codesee-io/oss-port pull request #128
Opened 2021-09-29 20:44 UTC by dnnrly

2021-09-29 23:23 UTC, NJalal7 requested changes
Hi Pascal, thank you for adding your projects to OSS Port. I've left a few minor comments, but the project pages are coming along really nicely—we're excited to help you find contributors soon!

2021-09-29 23:23 UTC, NJalal7 commented on projects/dnnrly/abbreviate.mdx
> +twitterUrl: pascaldoesgo
Could please update the Twitter entries for your projects with the full URL? Thanks!

2021-09-30 12:06 UTC, shaneakr approved these changes
Thanks so much for your contribution!

2021-09-30 18:08 UTC, dnnrly commented on projects/dnnrly/hoofli.mdx
> +  url: https://app.codesee.io/maps/d78e36e0-2173-11ec-9551-537c5ee7bea6
This has been rectified, please check again and make sure I've made it visible.

2021-09-30 18:47 UTC, dnnrly commented on projects/dnnrly/abbreviate.mdx
> +twitterUrl: pascaldoesgo
```suggestion
twitterUrl: https://twitter.com/pascaldoesgo
```

2021-09-30 18:59 UTC, ramonh commented on projects/dnnrly/hoofli.mdx
> +twitterUrl: pascaldoesgo
```suggestion
twitterUrl: https://twitter.com/pascaldoesgo
```

2021-09-30 19:00 UTC, ramonh commented on projects/dnnrly/httpref.mdx
> +twitterUrl: pascaldoesgo
```suggestion
twitterUrl: https://twitter.com/pascaldoesgo
```

2021-09-30 19:00 UTC, dnnrly commented on projects/dnnrly/hoofli.mdx
> +twitterUrl: pascaldoesgo
```suggestion
twitterUrl: https://twitter.com/pascaldoesgo
```

2021-09-30 19:00 UTC, ramonh commented on projects/dnnrly/puzzle-template.mdx
> +twitterUrl: pascaldoesgo
```suggestion
twitterUrl: https://twitter.com/pascaldoesgo
```

2021-09-30 19:01 UTC, dnnrly commented on projects/dnnrly/httpref.mdx
> +twitterUrl: pascaldoesgo
```suggestion
twitterUrl: https://twitter.com/pascaldoesgo
```

2021-09-30 19:01 UTC, dnnrly commented on projects/dnnrly/puzzle-template.mdx
> +twitterUrl: pascaldoesgo
```suggestion
twitterUrl: https://twitter.com/pascaldoesgo
```

2021-09-30 19:02 UTC, ramonh approved these changes

2021-09-30 19:04 UTC, merged

2021-09-30 19:15 UTC, dnnrly commented
Thank you all for your help!

❤️