Add Amazsell project
Codesee-io/oss-port pull request #151
Opened 2021-09-30 20:43 UTC by harryandriyan

Added Amazsell to the projects of OSS Port.

2021-10-01 12:39 UTC, ramonh commented on projects/harryandriyan/amazsell.mdx
> +  - Scraping tool
```suggestion
  - Scraping
```

Just noticed we already have the `Scraping` tag, so I'll go with this!

2021-10-01 12:39 UTC, ramonh commented on projects/harryandriyan/amazsell.mdx
> +  - Scraping tool
```suggestion
  - Scraping
```

Thanks for the suggestion! We'll use the already existing `Scraping` tag here.

2021-10-01 12:40 UTC, ramonh commented on projects/harryandriyan/amazsell.mdx
> +  - express
```suggestion
```

I think we can safely remove the `express` tag here, as it avoids bloating the list, and is covered by `NodeJS` :)

2021-10-01 12:40 UTC, ramonh commented on projects/harryandriyan/amazsell.mdx
> +  - Puppeteer
```suggestion
```

I think we can safely remove the `Puppeteer` tag here, as it avoids bloating the list :)

2021-10-01 12:41 UTC, ramonh requested changes
Thanks so much for your contribution @harryandriyan!

I made some suggestions, could you please take a look?

Thanks in advance!

2021-10-02 16:25 UTC, harryandriyan commented
Hi @ramonh I've committed the changes, Thanks

2021-10-02 16:31 UTC, ramonh approved these changes
Looks great, thank you!

Welcome to Port 🚢

2021-10-02 16:31 UTC, merged