Added my project 'FINADICT' to the list
Codesee-io/oss-port pull request #156
Opened 2021-10-01 09:33 UTC by subhayu99

2021-10-01 12:54 UTC, ramonh requested changes
Looking great, love the Map! To the point :)

Please see my feedback below. Thanks!

2021-10-01 12:54 UTC, ramonh commented on projects/subhayu99/finadict.mdx
> +  - What kind of contributions are you looking for?
Thanks so much for your contribution!

I'm afraid the Markdown came out a little odd in action. Please see this screenshot:
![image](https://user-images.githubusercontent.com/656318/135622847-83dd9186-a955-4c82-99cf-6c74a6df12e6.png)

Could you please take a look? Thanks in advance!

2021-10-01 14:45 UTC, subhayu99 commented on projects/subhayu99/finadict.mdx
> +  - What kind of contributions are you looking for?
Thank you for letting me know.
Actually, I edited the file on vim and forgot to check the actual output.😅
Will change it immediately.

2021-10-01 15:06 UTC, subhayu99 commented
@ramonh I have ammended the changes you requested and added a few more information on the page.

2021-10-02 15:27 UTC, ramonh commented on projects/subhayu99/finadict.mdx
> +  - What kind of contributions are you looking for?
Woopwoop! Fellow vim user 😄 

Cool, thanks for fixing!

2021-10-02 15:28 UTC, ramonh commented on projects/subhayu99/finadict.mdx
> +  - Finance Prediction
```suggestion
  - Finance
```

Hope it's fine if I shorten this to `Finance` so it's more reusable!

2021-10-02 15:28 UTC, ramonh approved these changes

2021-10-02 15:28 UTC, ramonh commented
Looks wonderful, thank you! Welcome to Port! 🚢

2021-10-02 15:29 UTC, merged

2021-10-02 15:30 UTC, subhayu99 commented
Thanks for approving ❤️