Add project shivammathur/setup-php
Codesee-io/oss-port pull request #176
Opened 2021-10-03 00:48 UTC by shivammathur

2021-10-03 13:09 UTC, ramonh requested changes
Thanks so much for putting up your project! 

I made some comments below. Could you take a look please?

2021-10-03 13:09 UTC, ramonh commented on projects/shivammathur/setup-php.mdx
> +  - PowerShell
```suggestion
  - Powershell
```

Fix minor Typo

2021-10-03 13:09 UTC, ramonh commented on projects/shivammathur/setup-php.mdx
> +  - Continuous integration
```suggestion
  - CI
```

Let's combine these into a shorter "CI" tag. We already list PHP as a language, so doing it as a tag is not necessary

2021-10-03 20:38 UTC, shivammathur commented on projects/shivammathur/setup-php.mdx
> +  - PowerShell
Changed to Powershell

2021-10-03 20:39 UTC, shivammathur commented on projects/shivammathur/setup-php.mdx
> +  - Continuous integration
Done

2021-10-04 05:27 UTC, ramonh approved these changes

2021-10-04 05:27 UTC, ramonh commented
Thanks @shivammathur everything looks great!

Welcome to Port 🚢

2021-10-04 05:27 UTC, merged