Added my Repos
Codesee-io/oss-port pull request #186
Opened 2021-10-05 16:48 UTC by ZigRazor

Signed-off-by: ZigRazor <zigrazor@gmail.com>

2021-10-05 19:56 UTC, ramonh requested changes
Thanks for the contribution! I made some suggestions down below

2021-10-05 19:56 UTC, ramonh commented on projects/ZigRazor/CXXAutomata.mdx
> +  - Library
Hi there!

None of these tags are in our template it seems. Could you please [take another look](https://raw.githubusercontent.com/Codesee-io/oss-port/main/projects/_template.mdx) at them? Programming languages go in the above `languages` section.

2021-10-05 19:56 UTC, ramonh commented on projects/ZigRazor/CXXAutomata.mdx
> +  url: https://app.codesee.io/maps/056943d0-25f6-11ec-b05a-410c40d81c25
Heya! Is it possible your Map is set to private? If so, could you please [update it](https://docs.codesee.io/en/latest/guide/#sharing-your-map) and replace this with the public URL?

Thanks!

2021-10-05 19:56 UTC, ramonh commented on projects/ZigRazor/CXXAutomata.mdx
> +A C++ library for simulating automata and Turing machines
Any chance this can be expanded? Maybe how to run the program? Link to docs, or something like this? 

Thanks in advance!

2021-10-06 08:41 UTC, ZigRazor commented on projects/ZigRazor/CXXAutomata.mdx
> +  - Library
i resolve in this commit

2021-10-06 08:41 UTC, ZigRazor commented on projects/ZigRazor/CXXAutomata.mdx
> +  url: https://app.codesee.io/maps/056943d0-25f6-11ec-b05a-410c40d81c25
i resolve in this commit

2021-10-06 08:41 UTC, ZigRazor commented on projects/ZigRazor/CXXAutomata.mdx
> +A C++ library for simulating automata and Turing machines
i resolve in this commit

2021-10-06 14:17 UTC, closed without merging