Added project by findingone
Codesee-io/oss-port pull request #250
Opened 2021-10-29 11:47 UTC by Findingone

2021-10-30 21:46 UTC, deammer requested changes

2021-10-30 21:46 UTC, deammer commented on projects/Findingone/a2oj-Implementation.mdx
> +  - (you may add custom entries, but please also add them to the canonical list in project/_template.mdx)
**issue (blocking):** this is the default content list in the template. Please fill out this information with content relevant to your project!

2021-10-30 21:46 UTC, deammer commented on projects/Findingone/a2oj-Implementation.mdx
> +    url: https://www.markdownguide.org/getting-started/
**issue (blocking):** this is also the content from the template. Please update it accordingly.

2021-10-30 21:46 UTC, deammer commented on projects/Findingone/a2oj-Implementation.mdx
> +**Hint:** you can write GitHub-flavored markdown just like you're used to. We even support Slack-style emojis :v:
**issue (blocking):** this is the default content from the template as well. Please update it accordingly!

We recommend explaining the purpose of the project, what goals are you trying to achieve, how to get started as a contributor, etc.

2022-01-12 12:28 UTC, ramonh commented
Closing due to inactivity.

2022-01-12 12:28 UTC, closed without merging