feat: added collcart website repo (merchandise based)
Codesee-io/oss-port pull request #87
Opened 2021-09-24 07:25 UTC by iamayushdas

2021-09-24 08:47 UTC, ramonh requested changes
Thank you so much for adding `collcart`, @iamayushdas!

I've made some questions and change requests.

Could you please also elaborate on some of the overview of the project as well as the contribution guidelines? Please see the template and other projects for ideas.

Thank you in advance!

2021-09-24 08:47 UTC, ramonh commented on projects/iamayushdas/cart.mdx
> +  - Social Activism
Could you please elaborate on how collcart is for Social Activism?

2021-09-24 08:47 UTC, ramonh commented on projects/iamayushdas/cart.mdx
> +  - Data Visualization
Could you please elaborate on how collcart is for Data Visualization?

2021-09-24 08:47 UTC, ramonh commented on projects/iamayushdas/cart.mdx
> +  - Merchandise
```suggestion
  - E-commerce
```

What do you think about using the tag E-commerce instead?

2021-09-24 08:47 UTC, ramonh commented on projects/iamayushdas/cart.mdx
> +#Its a merchandise for college societies plus college courses are also available on this.
```suggestion
# It's a merchandise for college societies plus college courses are also available on this.
```
Is it possible you meant for this to be a header?

2021-09-25 15:42 UTC, iamayushdas commented on projects/iamayushdas/cart.mdx
> +#Its a merchandise for college societies plus college courses are also available on this.
resolved

2021-09-25 15:42 UTC, iamayushdas commented on projects/iamayushdas/cart.mdx
> +  - Merchandise
resolved

2021-09-25 15:42 UTC, iamayushdas commented on projects/iamayushdas/cart.mdx
> +  - Data Visualization
resolved

2021-09-25 15:42 UTC, iamayushdas commented on projects/iamayushdas/cart.mdx
> +  - Social Activism
resolved

2021-09-25 15:43 UTC, iamayushdas reviewed
@ramonh have a look now

2021-09-28 13:20 UTC, ramonh commented
Looks great, thank you so much, @iamayushdas

2021-09-28 13:43 UTC, ramonh approved these changes

2021-09-28 13:44 UTC, merged