Include Project Password Manager by lpegoraro
Codesee-io/oss-port pull request #89
Opened 2021-09-24 13:26 UTC by lpegoraro

Adding my password-manager project.

2021-09-24 14:21 UTC, ramonh requested changes

2021-09-24 14:21 UTC, ramonh commented on projects/lpegoraro/password-manager.mdx
> +  url: https://app.codesee.io/maps/public/848e3630-1650-11ec-8bc1-7d4a4822cc27
Thank you for your contribution to port!

I noticed the Map here is from our sample. Did you mean to include a map for the password manager?

Feel free to give me a shout if you wanna go through it together :)

Otherwise, you can remove these links.

Thanks in advance!

2021-09-26 00:49 UTC, lpegoraro commented on projects/lpegoraro/password-manager.mdx
> +  url: https://app.codesee.io/maps/public/848e3630-1650-11ec-8bc1-7d4a4822cc27
Removing!

2021-09-28 13:13 UTC, ramonh commented on projects/lpegoraro/password-manager.mdx
> +  url: https://app.codesee.io/maps/public/848e3630-1650-11ec-8bc1-7d4a4822cc27
Thank you so much!

2021-09-28 13:13 UTC, ramonh approved these changes

2021-09-28 13:13 UTC, ramonh commented
Thank you so much for your contribution, @lpegoraro!

Welcome to the Port 🚢

2021-09-28 14:11 UTC, merged